version: "3.7"
services:
  app:
    build:
        context: ./
        dockerfile: dockerfile
    ports:
      - "8085:80"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: influence4you
      MYSQL_USER: root
      MYSQL_PASSWORD: password